export interface IOrders {
  order_id: number,
  total: number,
  status: number,
  createdAt: string,
  payment_method: number,
  discounts: number,
  shipping_cost: number,
  name: string,
  cpf: number, 
  client_id: number,
  zip_code: number,
  street: string,
  number: number,
  neighborhood: string,
  city: string,
  uf: string,
  product_id: number,
  title: string,
  quantity_served: number,
  image: string,
  price: number,
  flavor: number,
}